"""Phase 4 human-in-the-loop contracts and persistence helpers."""

from .models import (
    ApprovalAction,
    ApprovalRecord,
    ApprovalStatus,
    AuthorizationChannel,
    FindingStatus,
    ProjectSnapshot,
    RemediationPlan,
    TimelineEvent,
    TimelineEventType,
)
from .snapshots import (
    build_project_snapshot,
    changed_snapshot_files,
    snapshot_hash,
    snapshots_match,
)
from .store import EvidenceStore
from .redaction import (
    RawSecretError,
    SecretPersistenceError,
    assert_no_raw_secrets,
    contains_raw_secret,
    redact_evidence,
    redact_for_persistence,
    redact_mapping,
    redact_text,
    redact_value,
)
from .workflow import (
    ApprovalRequired,
    AuditRun,
    FindingNotFound,
    HUMAN_AUTHORIZATION_MESSAGE,
    HumanAuthorizationRequired,
    InvalidDisposition,
    ReleaseWorkflow,
    RemediationOutcome,
    ScopeViolation,
    StaleApproval,
    WorkflowError,
    plan_for_finding,
)

__all__ = [
    "ApprovalAction",
    "ApprovalRecord",
    "ApprovalStatus",
    "AuthorizationChannel",
    "FindingStatus",
    "ProjectSnapshot",
    "RemediationPlan",
    "TimelineEvent",
    "TimelineEventType",
    "ApprovalRequired",
    "AuditRun",
    "EvidenceStore",
    "HUMAN_AUTHORIZATION_MESSAGE",
    "HumanAuthorizationRequired",
    "RawSecretError",
    "SecretPersistenceError",
    "assert_no_raw_secrets",
    "contains_raw_secret",
    "FindingNotFound",
    "InvalidDisposition",
    "ReleaseWorkflow",
    "RemediationOutcome",
    "redact_evidence",
    "redact_for_persistence",
    "redact_mapping",
    "redact_text",
    "redact_value",
    "ScopeViolation",
    "StaleApproval",
    "WorkflowError",
    "build_project_snapshot",
    "changed_snapshot_files",
    "plan_for_finding",
    "snapshot_hash",
    "snapshots_match",
]
